mode: "dev"

http_server:
  address: "localhost:8080"
  timeout: 3s
  idle_timeout: 30s
  api:
    latest-version: v1
    layers:
      - b1
      - s2

tls:
  enabled: "true"
  cert_file: "./cert/server.crt"
  key_file: "./cert/server.key"

com_dir: "com/"