mode: "dev"

http_server:
  address: "192.168.1.176:8080"
  timeout: 3s
  idle_timeout: 30s
  api:
    latest-version: v1
    layers:
      - b1
      - s2

tls:
  enabled: false
  cert_file: "./cert/fullchain.pem"
  key_file: "./cert/privkey.pem"

internal:
  meta-dir: "./.meta/"

com_dir: "com/"


updates:
  enabled: true
  check-interval: 1h
  repository_url: "https://repo.serve.lv/raw/go-sally"