mode: "prod"

http_server:
  address: "0.0.0.0:8080"

tls:
  enabled: false
  cert_file: "./cert/fullchain.pem"
  key_file: "./cert/privkey.pem"

com_dir: "com/"

updates:
  enabled: false
  check-interval: 1h
  repository_url: "https://repo.serve.lv/raw/go-sally"